[package]
name = "live_server"
version = "0.0.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-files = "0.6.2"
actix-web = "4.4.0"
anyhow = "1.0.75"
async-std = "1.12.0"
chromiumoxide = "0.5.6"
current_platform = "0.2.0"
